baseURL = 'https://www.gokure.dev/'
languageCode = 'en-us'
title = 'Go Kure'

[params]
  # Global site notice
  disableInlineCopyToClipBoard = true
  # Custom header partial for site-wide notice - this appears at the top of content area
  customHeaderPartial = "custom-header.html"
  # Theme customization
  themeVariant = "relearn-dark"
  # Site-wide notice banner
  # This will appear on every page
  # Site notice - removed as it may conflict with custom header
  # [[params.notice]]
  #   level = "warning"
  #   title = "Work in Progress"
  #   content = "Kure is currently under active development and has not been released yet. APIs and features are subject to change."

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
  
  # Main documentation
  [[module.mounts]]
    source = "../kure/README.md"
    target = "content/overview/readme.md"
  
  [[module.mounts]]
    source = "../kure/docs/ARCHITECTURE.md"
    target = "content/architecture/details.md"

  # Package documentation
  # Launcher package - mount README as index and other docs separately
  [[module.mounts]]
    source = "../kure/pkg/launcher/README.md"
    target = "content/packages/launcher/_index.md"
  [[module.mounts]]
    source = "../kure/pkg/launcher/DESIGN.md"
    target = "content/packages/launcher/design.md"
  [[module.mounts]]
    source = "../kure/pkg/launcher/DESIGN-DETAILS.md"
    target = "content/packages/launcher/design-details.md"
  
  # Patch package - mount all docs as regular pages
  [[module.mounts]]
    source = "../kure/pkg/patch/DESIGN.md"
    target = "content/packages/patch/design.md"
  [[module.mounts]]
    source = "../kure/pkg/patch/ERROR_HANDLING.md"
    target = "content/packages/patch/error-handling.md"
  [[module.mounts]]
    source = "../kure/pkg/patch/PATCH_ENGINE_DESIGN.md"
    target = "content/packages/patch/patch-engine-design.md"
  [[module.mounts]]
    source = "../kure/pkg/patch/PATH_RESOLUTION.md"
    target = "content/packages/patch/path-resolution.md"
  
  [[module.mounts]]
    source = "../kure/pkg/stack/layout/README.md"
    target = "content/packages/layout/_index.md"
  
  [[module.mounts]]
    source = "../kure/pkg/workflow/README.md"
    target = "content/packages/workflow/_index.md"

  # Examples
  [[module.mounts]]
    source = "../kure/examples/patches/README.md"
    target = "content/examples/patches/_index.md"

  # Standard Hugo content
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
